{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "first-service.serviceAccountName" . }}
  labels:
{{ include "first-service.labels" . | nindent 4 }}
{{- end -}}
